### ISSUE TITLE
Tabular data should be TSV or CSV

### ISSUE THREAD

**Issue by trvrb** [blab/size-genetic-clusters#1]
It should be more convenient for users if the data files at `/data` are standard format. Either FASTA or sequences or TSV / CSV for tabular data. The current RDS files like https://github.com/blab/size-genetic-clusters/blob/main/data/mers/cluster_alloc_mers.rds can't be viewed online or in a text editor.

The intermediate file here 

```
Rscript ./get_cluster_distrib_from_fasta.R \
    "../data/synthetic-fasta.fasta" "../results/out_path_clust_size_distrib.rds"
```

Would also benefit from being TSV or CSV. Makes it easily inspectable.

Looks like RDS is a bit more efficient in terms of speed and size, but these are quite small and I wouldn't worry about this. And I could see a rationale to use RDS if it's a complex data format, but for tabular data I would stick with TSV or CSV.

**Comment by CecileTK** [comment]
The RDS objects is a list containing several elements, including a graph object that can not easily be saved with TSV or CSV. I could however save two elements, the RDS and a CSV where I would only write the cluster size distribution.

**Comment by CecileTK** [comment]
The RDS objects is a list containing several elements, including a graph object that can not easily be saved with TSV or CSV. I've added the option to save two files format (both RDS and CSV).

**Comment by trvrb** [comment]
Got it. Richard and I had a similar issue with a very early version of nextflu where it seemed at the time to make the most since to just use a `.pickle` object to store complex data. `.pickle` seems to be Python equivalent to R's `.rds`. However, this quickly became tedious and we moved to serializing data in standard formats. For Nextstrain this is FASTA for sequences, TSV for tabular data and JSON for more complex data. I believe that serialization should be in standard format whenever possible. I'd still recommend moving to plain text data files with JSON or whatever makes the most sense. What does this data actually look like in this case? (Me being confused on what data looks like is indicator of why I'm suggesting plain text)
